import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "n/utils/api";
import { SignIn, SignInButton, SignUp } from "@clerk/nextjs";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>MEOWWWWWWW</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SignInButton />
        <SignUp />
      </main>
    </>
  );
};

export default Home;
